### ISSUE TITLE
Cannot down load the pre-trained model

### ISSUE THREAD

**Issue by zhenxili96** [dvlab-research/Video-P2P#14]
hi, I tried to down the pre-trained model from this hugging face page [https://huggingface.co/spaces/video-p2p-library/Video-P2P-Demo](url). But the page shows:

```
Runtime error
Launch timed out, space was not healthy after 30 min
Container logs:

Fetching error logs...
```

Did you remove the pre-trained model in hugging face ?

**Comment by ShaoTengLiu** [comment]
Please download [sd1.5](https://huggingface.co/runwayml/stable-diffusion-v1-5) and fill the path at this [line](https://github.com/dvlab-research/Video-P2P/blob/c916cf4b10e7a105cc78688b41210a1543a8d9c9/configs/rabbit-jump-tune.yaml#L1C48-L1C69).
