### ISSUE TITLE
Error downloading model

### ISSUE THREAD

**Issue by gmongaras** [dvlab-research/Video-P2P#15]
Upon running `python run_tuning.py  --config="configs/rabbit-jump-tune.yaml"` I am getting the error
```
We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like /data/stable-diffusion/stable-diffusion-v1-5 is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
```

Is there somewhere I should download the model from? The README doesn't mention where to download a pretrained model and the huggingface space doesn't have any model checkpoints.

**Comment by ShaoTengLiu** [comment]
Please download [sd1.5](https://huggingface.co/runwayml/stable-diffusion-v1-5) and fill the path at this [line](https://github.com/dvlab-research/Video-P2P/blob/c916cf4b10e7a105cc78688b41210a1543a8d9c9/configs/rabbit-jump-tune.yaml#L1C48-L1C69).
